spring:
  application:
    name: OptionControlConsole
  datasource:
    url: jdbc:postgresql://localhost:5432/psql_db?currentSchema=option
    username: puser
    password: money7
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 300000
      max-lifetime: 600000
      minimum-idle: 2
      maximum-pool-size: 5


  liquibase:
    change-log: classpath:changelog/changelog-root.xml
    drop-first: false
    liquibase-schema: public
    default-schema: option

server:
  port: 8585
  context-path: /robot
  address: 0.0.0.0
