name: Deploy buy runner

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Stop and remove containers, networks
        run: docker stop option
             docker rm option
      - name: Remove unused data
        run: docker system prune -a
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker compose
        run: docker compose up -d
